version: '3.8'
services:
  db:
    container_name: weatherapp-db
    image: 763237209150.dkr.ecr.us-east-1.amazonaws.com/weatherapp-db:develop # Specify the desired image tag here
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: weatherapp
      MYSQL_USER: weatherapp
      MYSQL_PASSWORD: weatherapp
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - weatherapp
    restart: always

  redis:
    container_name: weatherapp-redis
    image: 763237209150.dkr.ecr.us-east-1.amazonaws.com/weatherapp-redis:develop # Specify the desired image tag here
    ports:
      - "6379:6379"
    expose:
      - "6379"
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    volumes:
      - ./redis-data:/data
    networks:
      - weatherapp
    restart: always

  ui:
    container_name: weatherapp-ui
    image: 763237209150.dkr.ecr.us-east-1.amazonaws.com/weatherapp-ui:develop # Specify the desired image tag here
    ports:
      - "3099:3000"
    expose:
      - "3000"
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    networks:
      - weatherapp
    restart: always

  weather:
    container_name: weatherapp-weather
    image: 763237209150.dkr.ecr.us-east-1.amazonaws.com/weatherapp-weather:develop # Specify the desired image tag here
    ports:
      - "5055:5000"
    expose:
      - "5000"
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - weatherapp
    restart: always

  auth:
    container_name: weatherapp-auth
    image: 763237209150.dkr.ecr.us-east-1.amazonaws.com/weatherapp-auth:develop # Specify the desired image tag here
    ports:
      - "8070:8080"
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    networks:
      - weatherapp
    expose:
      - "8080"
    restart: always

networks:
  weatherapp:
    driver: bridge